/**
 * Default empty values for data types
 *
 * Used for initial state when loading data, avoiding the need to
 * import the large mock data module into client bundles.
 */

import type {
  DashboardKPIs,
  ForecastTrendPoint,
  StageVelocity,
  FunnelStage,
  StuckDeal,
  HealthDistribution,
  ProcessBottleneck,
  CompetitiveLoss,
  HygieneSummary,
  HygieneAlert,
  HygieneTrendPoint,
  DealPrediction,
  LeadingIndicatorsSummary,
  TelemetrySummary,
  FunnelHandoffMetrics,
  CrossTeamActivity,
  RepPerformance,
  DriverComparison,
  ActivityMetrics,
  NextBestAction,
  CoachingInsight,
  PipelineDeal,
  SalesRep,
  QBRExecutiveSummary,
  QBRRepPerformance,
  QBRWinLossAnalysis,
  TerritorySummary,
  AccountScore,
  TerritoryBalance,
  WhiteSpaceAccount,
  CapacityPlanningSummary,
  RepCapacity,
  TeamCapacitySummary,
  RampCohortAnalysis,
  ScenarioSummary,
  WinRateScenario,
  DealSizeScenario,
  CycleTimeScenario,
  CustomerHealthSummary,
  CustomerHealth,
  ExpansionOpportunity,
  ChurnRiskAccount,
  ForecastSummary,
  ForecastBySegment,
  ForecastHistoryPoint,
  ForecastAccuracy,
  WinLossSummary,
  LossReason,
  WinFactor,
  CompetitiveBattle,
  WinLossBySegment,
  DealDeskSummary,
  DealApproval,
  DiscountAnalysis,
  CompPlanSummary,
  RepAttainment,
  AttainmentTrend,
  DataQualitySummary,
  DataQualityMetric,
  SyncStatus,
  AlertSummary,
  Alert,
  AlertRule,
} from '@/types'

// Dashboard defaults
export const defaultDashboardKPIs: DashboardKPIs = {
  quarterTarget: 0,
  closedWonAmount: 0,
  aiForecast: 0,
  aiForecastConfidence: 0,
  commitAmount: 0,
  commitConfidence: 0,
  gapToTarget: 0,
  gapPct: 0,
  coverageRatio: 0,
  riskLevel: 'Low',
  forecastChange1w: 0,
  commitChange1w: 0,
}

export const defaultHealthDistribution: HealthDistribution = {
  healthy: { count: 0, amount: 0, pct: 0 },
  monitor: { count: 0, amount: 0, pct: 0 },
  atRisk: { count: 0, amount: 0, pct: 0 },
  critical: { count: 0, amount: 0, pct: 0 },
  trend: 0,
}

export const defaultHygieneSummary: HygieneSummary = {
  totalOpportunities: 0,
  avgHygieneScore: 0,
  staleCloseDateCount: 0,
  singleThreadedCount: 0,
  missingNextStepsCount: 0,
  goneDarkCount: 0,
  missingChampionCount: 0,
  stalledStageCount: 0,
  overdueCommitCount: 0,
  heavyDiscountCount: 0,
  criticalCount: 0,
  highCount: 0,
  mediumCount: 0,
  lowCount: 0,
  totalAlerts: 0,
  cleanCount: 0,
  minorIssuesCount: 0,
  needsAttentionCount: 0,
  criticalHygieneCount: 0,
  criticalRevenueAtRisk: 0,
  highRevenueAtRisk: 0,
}

export const defaultLeadingIndicatorsSummary: LeadingIndicatorsSummary = {
  totalOpportunities: 0,
  totalPipeline: 0,
  probabilityWeightedPipeline: 0,
  avgWinProbability: 0,
  highProbCount: 0,
  highProbAmount: 0,
  mediumProbCount: 0,
  mediumProbAmount: 0,
  lowProbCount: 0,
  lowProbAmount: 0,
  highSlipRiskCount: 0,
  highSlipRiskAmount: 0,
  mediumSlipRiskCount: 0,
  mediumSlipRiskAmount: 0,
  totalSlipRiskAmount: 0,
  avgSlipRisk: 0,
  avgActivityRecency: 0,
  avgStakeholderEngagement: 0,
  avgVelocityScore: 0,
  aiForecastAdjustment: 0,
  forecastConfidence: 'Low',
  primaryRiskFactor: '',
}

export const defaultTelemetrySummary: TelemetrySummary = {
  totalLeads: 0,
  totalMqls: 0,
  totalSqls: 0,
  totalConverted: 0,
  mqlToSqlRate: 0,
  overallConversionRate: 0,
  avgResponseDays: 0,
  fastResponsePct: 0,
  slowResponseCount: 0,
  avgEngagementScore: 0,
  avgTouchesPerDeal: 0,
  fullEngagementPct: 0,
  fullEngagementHealthAvg: 0,
  singleEngagementHealthAvg: 0,
  healthDelta: 0,
  mqlToSqlHealth: 'AT_RISK',
  responseHealth: 'AT_RISK',
  speedToLeadHealth: 'AT_RISK',
  teamAlignmentHealth: 'AT_RISK',
  overallHealth: 'AT_RISK',
  primaryBottleneck: '',
  recommendation: '',
  snapshotDate: '',
}

// Rep Coaching defaults
export const defaultRepPerformance: RepPerformance = {
  repId: '',
  repName: '',
  managerName: '',
  region: '',
  segment: '',
  ytdAttainment: 0,
  winRate: 0,
  avgDealSize: 0,
  avgSalesCycle: 0,
  overallRank: 0,
  totalReps: 0,
  rankChange: 0,
  teamAvgWinRate: 0,
  teamAvgDealSize: 0,
  teamAvgCycle: 0,
  performanceTier: 'At Risk',
}

export const defaultActivityMetrics: ActivityMetrics = {
  totalActivities: 0,
  calls: 0,
  emails: 0,
  meetings: 0,
  demos: 0,
  avgDaily: 0,
  teamAvgDaily: 0,
  topPerformerDaily: 0,
  dailyTrend: [],
}

// QBR defaults
export const defaultQBRExecutiveSummary: QBRExecutiveSummary = {
  quarter: '',
  totalClosedWon: 0,
  totalQuota: 0,
  teamAttainment: 0,
  avgRepAttainment: 0,
  totalReps: 0,
  topPerformers: 0,
  atRiskReps: 0,
  totalPipeline: 0,
  avgHealthScore: 0,
  atRiskPipeline: 0,
  hygieneScore: 0,
  forecastAccuracy: 0,
  forecastGrade: '',
  winRate: 0,
  avgDealSize: 0,
  avgSalesCycle: 0,
  topLossReason: '',
  overallHealthScore: 0,
  healthGrade: '',
  insight1: '',
  insight2: '',
  insight3: '',
  recommendation1: '',
  recommendation2: '',
  recommendation3: '',
  generatedAt: '',
}

export const defaultQBRWinLossAnalysis: QBRWinLossAnalysis = {
  quarter: '',
  winsCount: 0,
  winsRevenue: 0,
  winsAvgDealSize: 0,
  winsAvgActivities: 0,
  winsAvgMeetings: 0,
  winsAvgCycle: 0,
  lossesCount: 0,
  lossesRevenue: 0,
  lossesAvgDealSize: 0,
  lossesAvgActivities: 0,
  lossesAvgMeetings: 0,
  lossesAvgCycle: 0,
  winRate: 0,
  topLossReason1: '',
  topLossReason1Pct: 0,
  topLossReason2: '',
  topLossReason2Pct: 0,
  topLossReason3: '',
  topLossReason3Pct: 0,
  activityDelta: 0,
  meetingDelta: 0,
  cycleDelta: 0,
}

// Territory defaults
export const defaultTerritorySummary: TerritorySummary = {
  totalTerritories: 0,
  totalAccounts: 0,
  avgAccountsPerTerritory: 0,
  avgPropensityScore: 0,
  highPropensityCount: 0,
  highPropensityRevenuePotential: 0,
  mediumPropensityCount: 0,
  lowPropensityCount: 0,
  balancedTerritories: 0,
  underloadedTerritories: 0,
  overloadedTerritories: 0,
  avgTerritoryBalance: 0,
  whiteSpaceAccounts: 0,
  whiteSpaceRevenuePotential: 0,
  topExpansionSegment: '',
  topExpansionIndustry: '',
  snapshotDate: '',
}

// Capacity defaults
export const defaultCapacityPlanningSummary: CapacityPlanningSummary = {
  totalReps: 0,
  rampedReps: 0,
  rampingReps: 0,
  developingReps: 0,
  totalQuota: 0,
  effectiveQuota: 0,
  totalClosedWon: 0,
  totalPipeline: 0,
  avgUtilization: 0,
  avgProductivity: 0,
  overCapacityCount: 0,
  underUtilizedCount: 0,
  teamAttainment: 0,
  coverageRatio: 0,
  rampCapacityLossPct: 0,
  capacityHealth: 'Healthy',
  hiringUrgency: 'Low',
  totalRecommendedHires: 0,
  totalHiringInvestment: 0,
  totalProjectedRevenue: 0,
  totalCapacityGap: 0,
  snapshotDate: '',
}

// Scenario defaults
export const defaultScenarioSummary: ScenarioSummary = {
  baselineRevenue: 0,
  baselineWinRate: 0,
  baselineDealSize: 0,
  winRateBestScenario: '',
  winRateUpside: 0,
  winRateUpsidePct: 0,
  dealSizeBestScenario: '',
  dealSizeUpside: 0,
  dealSizeUpsidePct: 0,
  cycleTimeBestScenario: '',
  cycleTimeUpside: 0,
  totalUpsidePotential: 0,
  snapshotDate: '',
}

// Customer Health defaults
export const defaultCustomerHealthSummary: CustomerHealthSummary = {
  totalCustomers: 0,
  totalArr: 0,
  avgHealthScore: 0,
  healthyCount: 0,
  monitorCount: 0,
  atRiskCount: 0,
  criticalCount: 0,
  healthyArr: 0,
  atRiskArr: 0,
  renewals90d: 0,
  renewalArr90d: 0,
  totalExpansionPotential: 0,
  highExpansionCount: 0,
  highExpansionValue: 0,
  churnRiskCount: 0,
  totalArrAtRisk: 0,
  netRetentionForecast: 0,
  snapshotDate: '',
}

// Forecasting defaults
export const defaultForecastSummary: ForecastSummary = {
  quota: 0,
  totalPipeline: 0,
  pipelineCoverage: 0,
  bottomUpForecast: 0,
  aiForecast: 0,
  bestCaseForecast: 0,
  highConfidenceAmount: 0,
  methodologyVariancePct: 0,
  recommendedMethod: '',
  methodAccuracy: 0,
  gapToTarget: 0,
  closedWonYtd: 0,
  topSegment: '',
  topSegmentForecast: 0,
  forecastConfidence: 'Low',
  weeksRemaining: 0,
  requiredWeeklyClose: 0,
  snapshotDate: '',
}

// Win/Loss defaults
export const defaultWinLossSummary: WinLossSummary = {
  totalClosed: 0,
  totalWon: 0,
  totalLost: 0,
  wonRevenue: 0,
  lostRevenue: 0,
  avgWonDealSize: 0,
  avgLostDealSize: 0,
  avgWonCycle: 0,
  avgLostCycle: 0,
  winRate: 0,
  lossRate: 0,
  winRateByValue: 0,
  dealSizeGap: 0,
  cycleGap: 0,
}

// Deal Desk defaults
export const defaultDealDeskSummary: DealDeskSummary = {
  pendingApprovals: 0,
  pendingValue: 0,
  avgApprovalTime: 0,
  slaBreachCount: 0,
  approvedToday: 0,
  rejectedToday: 0,
  avgDiscount: 0,
  discountTrend: 'stable',
  dealsByUrgency: {},
}

// Compensation defaults
export const defaultCompPlanSummary: CompPlanSummary = {
  totalQuota: 0,
  totalClosed: 0,
  teamAttainment: 0,
  avgRepAttainment: 0,
  onTrackCount: 0,
  atRiskCount: 0,
  overachieversCount: 0,
  totalCommissionPaid: 0,
  projectedCommission: 0,
  acceleratorEligible: 0,
}

// Data Quality defaults
export const defaultDataQualitySummary: DataQualitySummary = {
  overallScore: 0,
  completenessScore: 0,
  validityScore: 0,
  freshnessScore: 0,
  totalRecords: 0,
  issueCount: 0,
  criticalIssues: 0,
  lastSyncTime: '',
  syncStatus: 'healthy',
  trend: 'stable',
}

// Alerts defaults
export const defaultAlertSummary: AlertSummary = {
  totalActive: 0,
  criticalCount: 0,
  highCount: 0,
  mediumCount: 0,
  lowCount: 0,
  acknowledgedCount: 0,
  resolvedToday: 0,
  avgResolutionTime: 0,
}

// Sales rep default (for rep selector)
export const defaultSalesRep: SalesRep = {
  id: '',
  name: 'Loading...',
  team: '',
}

// Pipeline deal defaults (for coaching pipeline review)
export const defaultPipelineDeal: PipelineDeal = {
  id: '',
  accountName: '',
  amount: 0,
  healthScore: 0,
  primaryAction: 'call',
}
